version: '3.3'
services: 
  simpleTest:
    image: blazemeter/taurus
    volumes:
      - "$PWD/SimpleTaurusTest:/bzt-configs"
    command:
      - /bzt-configs/test.yml
      - -report
  fakeApiTest:
    image: blazemeter/taurus
    volumes:
      - "$PWD/apiTest:/bzt-configs"
    command:
      - /bzt-configs/execution.yml 
      - /bzt-configs/scenario.yml

